export const anos = [
  {
    id: 0,
    plat: "Engineers Platoon",
    name: "Capt. Dr. A Sursh Babu",
    rank: "Captain",
    src: "/images/anos/Engr_ANO_1.jpg",
    alt: "Capt. Dr. A Sursh Babu",
    desig: "Head of the Department",
    dept: "Dept. Manufacturing Engineering",
  },
  {
    id: 1,
    plat: "EME Platoon",
    name: "Lt. Dr. K Padmanabhan Panchu",
    rank: "Lieutenant",
    src: "/images/anos/EME_ANO.jpg",
    alt: "Lt. Dr. K Padmanabhan Panchu",
    desig: "Associate Professor",
    dept: "Dept. of Industrial Engineering",
  },
  {
    id: 2,
    plat: "Signals Platoon",
    name: "Lt. Dr. R Neelakandan",
    rank: "Lieutenant",
    src: "/images/anos/Sig_ANO.jpg",
    alt: "Lt. Dr. R Neelakandan",
    desig: "Professor",
    dept: "Dept. of Textile Technology",
  },
];
