export const anos = [
  {
    id: 0,
    plat: "Engineers Platoon",
    name: "Capt. Dr. A Suresh Babu",
    rank: "Captain",
    src: "/images/anos/Engr_ANO_1.jpg",
    alt: "Capt. Dr. A Sursh Babu",
    desig: "Professor",
    dept: "Dept. of Manufacturing Engineering",
    mobile: "98405 89469",
    email: "subaceg@gmail.com",
  },
  {
    id: 1,
    plat: "EME Platoon",
    name: "Lt. Dr. K Padmanabhan Panchu",
    rank: "Lieutenant",
    src: "/images/anos/EME_ANO.jpg",
    alt: "Lt. Dr. K Padmanabhan Panchu",
    desig: "Associate Professor",
    dept: "Dept. of Industrial Engineering",
    mobile: "89399 34561",
    email: "panchu81@gmail.com",
  },
  {
    id: 2,
    plat: "Signals Platoon",
    name: "Lt. Dr. R Neelakandan",
    rank: "Lieutenant",
    src: "/images/anos/Sig_ANO.jpg",
    alt: "Lt. Dr. R Neelakandan",
    desig: "Professor and Head",
    dept: "Dept. of Textile Technology",
    mobile: "94444 11754",
    email: "neelakandanauc@gmail.com",
  },
];
