export const currentBatch = {
  year: "2022-2023",
  csuo: {
    id: 0,
    name: "CSUO Pramoth Kumar A",
    src: "/images/leaders/csuo.jpg",
    desig: "Student",
    plat: "Signals Platoon",
    rank: "Cadet Senior Under Officer",
    dept: "Dept. of Leather Technology",
  },
  cuo1: {
    id: 1,
    name: "CUO Karen Jerusha J",
    src: "/images/leaders/cuo1.jpg",
    desig: "Student",
    plat: "Engineers Platoon",
    rank: "Cadet Under Officer",
    dept: "Dept. of Mechanical Engineering",
  },
  cuo2: {
    id: 2,
    name: "CUO Reshma S",
    src: "images/leaders/cuo2.jpg",
    desig: "Student",
    plat: "EME Platoon",
    rank: "Cadet Under Officer",
    dept: "Dept. of Electronics and Communication Engineering",
  },
  cuo3: {
    id: 3,
    name: "CUO Elasukumaran E",
    src: "images/leaders/cuo3.jpg",
    desig: "Student",
    plat: "Signals Platoon",
    rank: "Cadet Under Officer",
    dept: "Dept. of Ceramic Technology",
  },
  cqms: {
    id: 4,
    name: "CQMS Pearlina Marie Rein K",
    src: "images/leaders/cqms.jpg",
    desig: "Student",
    plat: "Signals Platoon",
    rank: "Company Quarter Master Sergeant",
    dept: "Dept. of Applied Science and Technology",
  },
  csm: {
    id: 5,
    name: "CSM Jayaharish M R",
    src: "images/leaders/csm.jpg",
    desig: "Student",
    plat: "Engineers Platoon",
    rank: "Company Sergeant Major",
    dept: "Dept. of Electronics and Communication Engineering",
  },
};
