export const currentBatch = {
  year: "2022-2023",
  csuo: {
    id: 0,
    name: "CSUO Pramoth Kumar A",
    src: "",
    alt: "",
    plat: "Signals Platoon",
    rank: "Cadet Senior Under Officer",
    dept: "",
  },
  cuo1: {
    id: 1,
    name: "CUO Karen Jerusha J",
    src: "",
    alt: "",
    plat: "Engineers Platoon",
    rank: "Cadet Under Officer",
    dept: "",
  },
  cuo2: {
    id: 2,
    name: "CUO Reshma S",
    src: "",
    alt: "",
    plat: "EME Platoon",
    rank: "Cadet Under Officer",
    dept: "",
  },
  cuo3: {
    id: 3,
    name: "CUO Elasukumaran E",
    src: "",
    alt: "",
    plat: "Signals Platoon",
    rank: "Cadet Under Officer",
    dept: "",
  },
  cqms: {
    id: 4,
    name: "CQMS Pearlina Marie Rein K",
    src: "",
    alt: "",
    plat: "Signals Platoon",
    rank: "Company Quarter Master Sergeant",
    dept: "",
  },
  csm: {
    id: 5,
    name: "CSM Jayaharish M R",
    src: "",
    alt: "",
    plat: "Engineers Platoon",
    rank: "Company Sergeant Major",
    dept: "",
  },
};
