export const special_occasions = [
  {
    id: 0,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi1.jpg",
    alt: "Avadi Tank Expo",
    height: 900,
    width: 1600,
  },
  {
    id: 1,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi2.jpg",
    alt: "Avadi Tank Expo",
    height: 900,
    width: 1600,
  },
  {
    id: 2,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi3.jpg",
    alt: "Avadi Tank Expo",
    height: 900,
    width: 1600,
  },
  {
    id: 3,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi4.jpg",
    alt: "Avadi Tank Expo",
    height: 900,
    width: 1600,
  },
  {
    id: 4,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi5.jpg",
    alt: "Avadi Tank Expo",
    height: 900,
    width: 1600,
  },
  {
    id: 5,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi6.jpg",
    alt: "Avadi Tank Expo",
    height: 900,
    width: 1600,
  },
  {
    id: 6,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi7.jpg",
    alt: "Avadi Tank Expo",
    height: 1824,
    width: 4000,
  },
  {
    id: 7,
    title: "Avadi Tank Expo",
    src: "/images/gallery/special_occasions/avadi8.jpg",
    alt: "Avadi Tank Expo",
    height: 900,
    width: 1600,
  },
  {
    id: 8,
    title: "B-Certificate Exam",
    src: "/images/gallery/special_occasions/bcert1.jpg",
    alt: "Camps & Training",
    height: 1824,
    width: 4000,
  },
  {
    id: 9,
    title: "B-Certificate Exam",
    src: "/images/gallery/special_occasions/bcert2.jpg",
    alt: "Camps & Training",
    height: 2112,
    width: 4608,
  },
  {
    id: 10,
    title: "C-Certificate Exam",
    src: "/images/gallery/special_occasions/ccert1.jpg",
    alt: "Camps & Training",
    height: 1000,
    width: 750,
  },
  {
    id: 11,
    title: "C-Certificate Exam",
    src: "/images/gallery/special_occasions/ccert2.jpg",
    alt: "Camps & Training",
    height: 1824,
    width: 4000,
  },
  {
    id: 12,
    title: "NBA Mock Visit",
    src: "/images/gallery/special_occasions/nbamock1.jpg",
    alt: "Camps & Training",
    height: 1536,
    width: 2048,
  },
  {
    id: 13,
    title: "NBA Mock Visit",
    src: "/images/gallery/special_occasions/nbamock2.jpg",
    alt: "Camps & Training",
    height: 3000,
    width: 3000,
  },
  {
    id: 14,
    title: "NBA Mock Visit",
    src: "/images/gallery/special_occasions/nbamock3.jpg",
    alt: "Camps & Training",
    height: 3000,
    width: 3000,
  },
  {
    id: 15,
    title: "NBA Mock Visit",
    src: "/images/gallery/special_occasions/nbamock4.jpg",
    alt: "Camps & Training",
    height: 1536,
    width: 2048,
  },
  {
    id: 16,
    title: "NBA Mock Visit",
    src: "/images/gallery/special_occasions/nbamock5.jpg",
    alt: "Camps & Training",
    height: 1536,
    width: 2048,
  },
  {
    id: 17,
    title: "Statue Cleaning",
    src: "/images/gallery/special_occasions/statclean1.jpg",
    alt: "Camps & Training",
    height: 2610,
    width: 4640,
  },
  {
    id: 18,
    title: "Statue Cleaning",
    src: "/images/gallery/special_occasions/statclean2.jpg",
    alt: "Camps & Training",
    height: 2610,
    width: 4640,
  },
  {
    id: 19,
    title: "Statue Cleaning",
    src: "/images/gallery/special_occasions/statclean3.jpg",
    alt: "Camps & Training",
    height: 960,
    width: 1280,
  },
  {
    id: 20,
    title: "Statue Cleaning",
    src: "/images/gallery/special_occasions/statclean4.jpg",
    alt: "Camps & Training",
    height: 960,
    width: 1280,
  },
  {
    id: 21,
    title: "Swarmin Vijay Diwas",
    src: "/images/gallery/special_occasions/swarmin1.jpg",
    alt: "Camps & Training",
    height: 2112,
    width: 4608,
  },
  {
    id: 22,
    title: "Swarmin Vijay Diwas",
    src: "/images/gallery/special_occasions/swarmin2.jpg",
    alt: "Camps & Training",
    height: 2112,
    width: 4608,
  },
  {
    id: 23,
    title: "Swarmin Vijay Diwas",
    src: "/images/gallery/special_occasions/swarmin3.jpg",
    alt: "Camps & Training",
    height: 2112,
    width: 4608,
  },
];

export const republic_day = [
  {
    id: 0,
    title: "Republic Day",
    src: "/images/gallery/republic_day/1.jpg",
    alt: "Republic Day",
    height: 1080,
    width: 1920,
  },
  {
    id: 1,
    title: "Republic Day",
    src: "/images/gallery/republic_day/2.jpg",
    alt: "Republic Day",
    height: 2112,
    width: 4608,
  },
  {
    id: 2,
    title: "Republic Day",
    src: "/images/gallery/republic_day/3.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 3,
    title: "Republic Day",
    src: "/images/gallery/republic_day/4.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 4,
    title: "Republic Day",
    src: "/images/gallery/republic_day/5.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 5,
    title: "Republic Day",
    src: "/images/gallery/republic_day/6.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 6,
    title: "Republic Day",
    src: "/images/gallery/republic_day/7.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 7,
    title: "Republic Day",
    src: "/images/gallery/republic_day/8.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 8,
    title: "Republic Day",
    src: "/images/gallery/republic_day/9.jpg",
    alt: "Republic Day",
    height: 1080,
    width: 1920,
  },
  {
    id: 9,
    title: "Republic Day",
    src: "/images/gallery/republic_day/10.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 10,
    title: "Republic Day",
    src: "/images/gallery/republic_day/11.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 11,
    title: "Republic Day",
    src: "/images/gallery/republic_day/12.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 12,
    title: "Republic Day",
    src: "/images/gallery/republic_day/13.jpg",
    alt: "Republic Day",
    height: 1080,
    width: 1920,
  },
  {
    id: 13,
    title: "Republic Day",
    src: "/images/gallery/republic_day/14.jpg",
    alt: "Republic Day",
    height: 2112,
    width: 4608,
  },
  {
    id: 14,
    title: "Republic Day",
    src: "/images/gallery/republic_day/r1.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 15,
    title: "Republic Day",
    src: "/images/gallery/republic_day/r2.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 16,
    title: "Republic Day",
    src: "/images/gallery/republic_day/r3.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 17,
    title: "Republic Day",
    src: "/images/gallery/republic_day/r4.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 18,
    title: "Republic Day",
    src: "/images/gallery/republic_day/r5.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
  {
    id: 19,
    title: "Republic Day",
    src: "/images/gallery/republic_day/r6.jpg",
    alt: "Republic Day",
    height: 1824,
    width: 4000,
  },
];
export const independence_day = [
  {
    id: 0,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_1.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 1,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_2.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 2,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_3.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 3,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_4.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 4,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_5.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 5,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_6.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },

  {
    id: 6,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_7.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 7,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_8.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 8,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_9.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 9,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_10.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 10,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_11.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 11,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_12.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 12,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_13.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 13,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_14.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 14,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_15.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 15,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_16.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 16,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_17.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
  {
    id: 17,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_18.jpg",
    alt: "Independence Day",
    height: 3000,
    width: 4000,
  },
  {
    id: 18,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_19.jpg",
    alt: "Independence Day",
    height: 1824,
    width: 4000,
  },

  {
    id: 19,
    title: "Independece Day",
    src: "/images/gallery/independence_day/i22_20.jpg",
    alt: "Independence Day",
    height: 4000,
    width: 6000,
  },
];

export const events_campaigns = [
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/angdaan1.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/angdaan2.jpg",
    alt: "Events&Campaigns",
    height: 4000,
    width: 6000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/angdaan3.jpg",
    alt: "Events&Campaigns",
    height: 4000,
    width: 6000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/angdaan4.jpg",
    alt: "Events&Campaigns",
    height: 4000,
    width: 6000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/angdaan5.jpg",
    alt: "Events&Campaigns",
    height: 4000,
    width: 6000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/angdaan6.jpg",
    alt: "Events&Campaigns",
    height: 1824,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/cadprev1.jpg",
    alt: "Events&Campaigns",
    height: 2160,
    width: 3840,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/cadprev2.jpg",
    alt: "Events&Campaigns",
    height: 2160,
    width: 3840,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/cycral1.jpg",
    alt: "Events&Campaigns",
    height: 4000,
    width: 3000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/cycral2.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/cycral3.jpg",
    alt: "Events&Campaigns",
    height: 1824,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/nbamock1.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 3000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/nbamock2.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 3000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/nbamock3.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 3000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/psagar1.jpg",
    alt: "Events&Campaigns",
    height: 1824,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/psagar2.jpg",
    alt: "Events&Campaigns",
    height: 1824,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/psagar3.jpg",
    alt: "Events&Campaigns",
    height: 1824,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/yoga1.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/yoga2.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/yoga3.jpg",
    alt: "Events&Campaigns",
    height: 3000,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/yoga4.jpg",
    alt: "Events&Campaigns",
    height: 1824,
    width: 4000,
  },
  {
    id: 0,
    title: "Events&Campaigns",
    src: "/images/gallery/events_campaigns/yoga5.jpg",
    alt: "Events&Campaigns",
    height: 1824,
    width: 4000,
  },
];

export const camps_trainings = [
  {
    id: 0,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/cadrecamp1.jpg",
    alt: "Camps&Trainings",
    height: 1540,
    width: 3155,
  },
  {
    id: 1,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/cadrecamp2.jpg",
    alt: "Camps&Trainings",
    height: 1764,
    width: 3022,
  },
  {
    id: 2,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/cadrecamp3.jpg",
    alt: "Camps&Trainings",
    height: 1890,
    width: 4000,
  },
  {
    id: 3,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/cadrecamp4.jpg",
    alt: "Camps&Trainings",
    height: 1786,
    width: 3407,
  },
  {
    id: 4,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/cadrecamp5.jpg",
    alt: "Camps&Trainings",
    height: 1352,
    width: 3440,
  },
  {
    id: 5,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/ebsbo1.jpg",
    alt: "Camps&Trainings",
    height: 1080,
    width: 1920,
  },
  {
    id: 6,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/ebsbo2.jpg",
    alt: "Camps&Trainings",
    height: 1080,
    width: 1920,
  },
  {
    id: 7,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/ebsbo3.jpg",
    alt: "Camps&Trainings",
    height: 1080,
    width: 1920,
  },
  {
    id: 8,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/firing1.jpg",
    alt: "Camps&Trainings",
    height: 3000,
    width: 4000,
  },
  {
    id: 9,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/firing2.jpg",
    alt: "Camps&Trainings",
    height: 3000,
    width: 4000,
  },
  {
    id: 10,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/melmaru1.jpeg",
    alt: "Camps&Trainings",
    height: 960,
    width: 1280,
  },
  {
    id: 11,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/melmaru2.jpeg",
    alt: "Camps&Trainings",
    height: 3456,
    width: 4608,
  },
  {
    id: 12,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/melmaru3.jpeg",
    alt: "Camps&Trainings",
    height: 960,
    width: 1280,
  },
  {
    id: 13,
    title: "Camps&Trainings",
    src: "/images/gallery/camps/melmaru4.jpeg",
    alt: "Camps&Trainings",
    height: 1970,
    width: 4160,
  },
];
export const sports_activity = [
  {
    id: 0,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain1.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
  {
    id: 1,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain2.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
  {
    id: 2,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain3.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
  {
    id: 3,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain4.jpg",
    alt: "SportActivity",
    height: 4000,
    width: 1824,
  },
  {
    id: 4,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain5.jpg",
    alt: "SportActivity",
    height: 3000,
    width: 4000,
  },
  {
    id: 5,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain6.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
  {
    id: 6,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain7.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
  {
    id: 7,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/obtrain8.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
  {
    id: 8,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/prun1.jpg",
    alt: "SportActivity",
    height: 780,
    width: 1052,
  },
  {
    id: 9,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/prun2.jpg",
    alt: "SportActivity",
    height: 780,
    width: 1052,
  },
  {
    id: 10,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/sparade1.jpg",
    alt: "SportActivity",
    height: 3000,
    width: 4000,
  },
  {
    id: 11,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/sparade2.jpg",
    alt: "SportActivity",
    height: 3000,
    width: 4000,
  },
  {
    id: 12,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/sparade3.jpg",
    alt: "SportActivity",
    height: 3000,
    width: 4000,
  },
  {
    id: 13,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/sparade4.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
  {
    id: 14,
    title: "SportActivity",
    src: "/images/gallery/sports_activities/sparade5.jpg",
    alt: "SportActivity",
    height: 1824,
    width: 4000,
  },
];
