export const posters = [
  { id: 0, src: "/images/posters/walk_for_a_cause_2021.jpg" },
  { id: 1, src: "/images/posters/army_day_2021.jpg" },
  { id: 2, src: "/images/posters/doodling_contest_2021.jpg" },
  { id: 3, src: "/images/posters/poem_competition_1_2021.jpg" },
  { id: 4, src: "/images/posters/inkdown_the_picture_2021.jpg" },
  { id: 5, src: "/images/posters/republic_day_2021.jpg" },
  { id: 6, src: "/images/posters/essay_competition_2021.jpg" },
  { id: 7, src: "/images/posters/kargil_vijay_diwas_2021.jpg" },
  { id: 8, src: "/images/posters/independence_day_2021.jpg" },
  { id: 9, src: "/images/posters/cavalry_day_2021.jpg" },
  { id: 10, src: "/images/posters/gunners_day_2021.jpg" },
  { id: 11, src: "/images/posters/eco_run_2021.jpg" },
  {
    id: 12,
    src: "/images/posters/military_nursing_services_2021.jpg",
  },
  { id: 13, src: "/images/posters/gandhi_jayanthi_2021.jpg" },
  { id: 14, src: "/images/posters/airforce_day_2021.jpg" },
  { id: 15, src: "/images/posters/wolrd_students_day_2021.jpg" },
  { id: 16, src: "/images/posters/constitution_day_2021.jpg" },
  { id: 17, src: "/images/posters/ncc_day_2021.jpg" },
  { id: 18, src: "/images/posters/navy_day_2021.jpg" },
  { id: 19, src: "/images/posters/poem_competition_2021.jpg" },
  { id: 20, src: "/images/posters/webinar_on_unity_&_peace_2021.jpg" },
  { id: 21, src: "/images/posters/talk_on_social_harmony_2021.jpg" },
  {
    id: 22,
    src: "/images/posters/career_armed_forces_2021.jpg",
  },
  { id: 23, src: "/images/posters/army_day_2022.jpeg" },
  { id: 25, src: "/images/posters/know_your_laws_2022.jpeg" },
  { id: 26, src: "/images/posters/artography_2022.jpg" },
  { id: 24, src: "/images/posters/pakram_diwas_2022.jpeg" },
  { id: 27, src: "/images/posters/republic_day_2022.jpeg" },
  { id: 28, src: "/images/posters/martyrs_day_2022.jpeg" },
  { id: 29, src: "/images/posters/angdaan_2022.jpeg" },
  { id: 30, src: "/images/posters/yoga_day_2022.jpeg" },
  { id: 31, src: "/images/posters/kargil_vijay_diwas_2022.jpeg" },
  { id: 32, src: "/images/posters/airforce_day_2022.jpeg" },
  { id: 33, src: "/images/posters/open_call_2022.jpeg" },
  { id: 34, src: "/images/posters/udhira_2022.jpeg" },
  { id: 35, src: "/images/posters/navy_day_2022.jpeg" },
  { id: 36, src: "/images/posters/army_day_2023.jpg" },
  { id: 37, src: "/images/posters/yoga_day_2023.jpeg" },
];
