import "./globals.css";
import { Inter } from "next/font/google";
import RootComponent from "./ThemeWrapper.tsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NCC | Anna University",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootComponent>{children}</RootComponent>
      </body>
    </html>
  );
}
