"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import AppBar from "@/components/AppBar/AppBar";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NCC | Anna University",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider enableSystem defaultTheme="dark" attribute="class">
          <AppBar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
