const camps = [
  {
    id: 0,
    title: "Ek Bharat Shreshtha Bharat",
    shortTitle: "EBSB",
    desc: `EBSB (Ek Bharat Shreshtha Bharat) is an initiative by the Government of India aimed at promoting cultural integration and understanding between different states and union territories of the country. The EBSB camp organized by the National Cadet Corps (NCC) focuses on fostering unity in diversity and celebrating the rich cultural heritage of India.`,
    duration: `7 - 10 days`,
    activities: [
      "Cultural Performances",
      "Presentations & Discussions",
      "Excursions & Tours",
      "Workshops & Demonstrations",
      "Team Building Activities",
    ],
  },
  {
    id: 1,
    title: "Basic Leadership Camp",
    shortTitle: "BLC",
    desc: `BLC (Basic Leadership Camp) is a camp organized by the National Cadet Corps (NCC) that focuses on developing leadership skills, teamwork, and personal growth among cadets. The camp provides a foundation for cadets to understand the principles of leadership and gain practical experience in leading and managing a team.`,
    duration: `7 - 10 days`,
    activities: [
      "Leadership Workshops",
      "Team-Building Exercises",
      "Drill & Discipline",
      "Leadership Games",
      "Fitness Training",
    ],
  },
  {
    id: 2,
    title: "Combined Annual Training Camp",
    shortTitle: "CATC",
    desc: `The Combined Annual Training Camp (CATC) is an important and significant camp organized by the National Cadet Corps (NCC). It is an annual event that brings together cadets from different units and institutions to undergo comprehensive training and participate in various activities.`,
    duration: `10 - 15 days`,
    activities: [
      "Military Training",
      "Drill & Discipline",
      "Physical Training",
      "Cultural Events",
      "Campfire & Bonding",
    ],
  },
  {
    id: 3,
    title: "Army Attachment Camp",
    shortTitle: "AAC",
    desc: `The Army Attachment Camp is a specialized camp organized by the National Cadet Corps (NCC) in collaboration with the Indian Army. It provides NCC cadets with an opportunity to experience the life of an Indian Army soldier, gain insights into military operations, and develop a deeper understanding of the army's role in national security.`,
    duration: `About 2 weeks`,
    activities: [
      "Military Training",
      "Observe Army Exercises",
      "Weapon Training",
      "Equipment Display",
      "Field Visits",
    ],
  },
  {
    id: 4,
    title: "Republic Day Camp",
    shortTitle: "RDC",
    desc: `The Republic Day Camp (RDC) is a highly prestigious camp organized by the National Cadet Corps (NCC) in India. It is conducted in Delhi, usually during the month of January, to celebrate the Republic Day of India. The RDC camp is a culmination of rigorous selection processes and represents the pinnacle of achievement for NCC cadets.`,
    duration: `25 - 30 days`,
    activities: [
      "Ceremonial Training",
      "Cultural Events",
      "Drill Training",
      "Educational Tours",
      "Republic Day Parade",
    ],
  },
  {
    id: 5,
    title: "Thal Sainik Camp",
    shortTitle: "TSC",
    desc: `Thal Sainik Camp (TSC) is a prestigious 12-day camp conducted in Delhi every year during the late autumn season. It brings together selected cadets from all 17 NCC directorates, with 30+3 cadets representing each directorate. The selection process involves three pre-TSC camps, each lasting for 10-12 days, conducted at weekly intervals.`,
    duration: `10 - 12 days`,
    activities: [
      "Obstacle Course",
      "Rifle Firing",
      "Map Reading",
      "Home Nursing",
    ],
  },
];

export default camps;
